### ISSUE TITLE
Add neclib, xarray, necstdb to pyproject.toml

### ISSUE THREAD

**Issue by r-yamada1998** [necst-telescope/nercst#10]
**Motivation**

- Use @KaoruNishikawa 's high-spec machine to resolve dependencies

**What should be realised**
Enable
```python
import xarray
import necstdb
import neclib
```

**Comment by KaoruNishikawa** [comment]
@r-yamada1998 
Now `neclib` only supports `python >=3.8`.
Is the support for Python 3.7 needed for THIS package?
Adding support for the Python versions in `neclib` is also possible.

**Comment by r-yamada1998** [comment]
@KaoruNishikawa 
In fact, supportation of 3.7 or earlier is just a temporary implementation. No need to support older versions of python.
Let's purge 3.7.
